[tool.poetry]
name = "fukuoka"
version = "0.1.0"
description = ""
authors = ["taaaaho <taaaaho@gmail.com>"]

[tool.poetry.dependencies]
python = "^2.7"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
